INSERT INTO CART(USER_NAME) VALUES('Jess');
INSERT INTO CART(USER_NAME) VALUES('Riel');

INSERT INTO ITEM (NAME, PRICE, STOCK_QUANTITY) VALUES ('Cellphone', 200.45, 10);
INSERT INTO ITEM (NAME, PRICE, STOCK_QUANTITY) VALUES ('Comb',      1.679,  10);
INSERT INTO ITEM (NAME, PRICE, STOCK_QUANTITY) VALUES ('Bag',       30.45,  10);