INSERT INTO CART(USER_NAME) VALUES('Jess');
INSERT INTO CART(USER_NAME) VALUES('Riel');

INSERT INTO ITEM (NAME, PRICE) VALUES ('Cellphone', 200.45);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Comb', 1.679);
INSERT INTO ITEM (NAME, PRICE) VALUES ('Bag', 30.45);